### ISSUE TITLE
Failed to lookup symbol 'PLGNCreateClaim': dlsym(RTLD_DEFAULT, PLGNCreateClaim): symbol not found

### ISSUE THREAD

**Issue by bibash28** [iden3/polygonid-flutter-sdk#217]
Called 
```
    final sdk = PolygonIdSdk.I;
    final identity = await sdk.identity.createIdentity(
      blockchain: 'polygon',
      network: 'main',
    );
```

The issue is in iOS..

Works in Android..
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'PLGNCreateClaim': dlsym(RTLD_DEFAULT, PLGNCreateClaim): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      NativePolygonIdCoreLib._PLGNCreateClaimPtr
native_polygonidcore.dart:3148
#2      NativePolygonIdCoreLib._PLGNCreateClaimPtr (package:polygonid_flutter_sdk/common/libs/polygonidcore/native_polygonidcore.dart)
native_polygonidcore.dart:1
#3      NativePolygonIdCoreLib._PLGNCreateClaim
native_polygonidcore.dart:3149
#4      NativePolygonIdCoreLib._PLGNCreateClaim (package:polygonid_flutter_sdk/common/libs/polygonidcore/native_polygonidcore.dart)
native_polygonidcore.dart:1
#5      NativePolygonIdCoreLib.PLGNCreateClaim
native_polygonidcore.dart:3136
#6      PolygonIdCoreCredential.createClaim
pidcore_credential.dart:19
#7      LibPolygonIdCoreCredentialDataSource.issueClaim
lib_pidcore_credential_data_source.dart:28
#8      LocalClaimDataSource.getAuthClaim
local_claim_data_source.dart:14
#9      CredentialRepositoryImpl.getAuthClaim
credential_repository_impl.dart:169
#10     GetAuthClaimUseCase.execute
get_auth_claim_use_case.dart:14
#11     GetIdentityAuthClaimUseCase.execute.<anonymous closure>
get_identity_auth_claim_use_case.dart:21
<asynchronous suspension>
#12     Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#13     AddIdentityUseCase.execute
add_identity_use_case.dart:43
<asynchronous suspension>
#14     PolygonId.createIdentity
polygonid.dart:38
<asynchronous suspension>
```

**Comment by bibash28** [comment]
The issue was solved after the following configuration in ios/Podfile. It would help community if it is included in the documentation.
```
post_install do |installer|  
  installer.pods_project.targets.each do |target|
    ...
    end
    # polygon-setup
    if target.name == "Pods-Runner"
      puts "Updating #{target.name} OTHER_LDFLAGS"
      target.build_configurations.each do |config|
                      xcconfig_path = config.base_configuration_reference.real_path
                      xcconfig = File.read(xcconfig_path)
                      new_xcconfig = xcconfig.sub('OTHER_LDFLAGS = $(inherited)', 'OTHER_LDFLAGS = $(inherited) -force_load "${PODS_ROOT}/../.symlinks/plugins/polygonid_flutter_sdk/ios/librapidsnark.a" -force_load "${PODS_ROOT}/../.symlinks/plugins/polygonid_flutter_sdk/ios/libwitnesscalc_authV2.a" -force_load "${PODS_ROOT}/../.symlinks/plugins/polygonid_flutter_sdk/ios/libwitnesscalc_credentialAtomicQueryMTPV2.a" -force_load "${PODS_ROOT}/../.symlinks/plugins/polygonid_flutter_sdk/ios/libwitnesscalc_credentialAtomicQuerySigV2.a" -force_load "${PODS_ROOT}/../.symlinks/plugins/polygonid_flutter_sdk/ios/libgmp.a" -force_load "${PODS_ROOT}/../.symlinks/plugins/polygonid_flutter_sdk/ios/libpolygonid.a"')
                      File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
         end
     end
  end
end
```
@eberger727 Check this out..

**Comment by rauljareno** [comment]
thanks @bibash28 we will include it in the documentation :)
